server:
  port: 8777
spring:
  redis:
        block-when-exhausted: true
        database: 1
        host: 192.168.242.128
        jedis:
          pool:
            max-active: 1024
            max-idle: 200
            max-wait: 10000
            min-idle: 0
        password: '123456'
        port: 6379
        timeout: 10000  